baseURL = "http://localhoost/"
languageCode = "ko-kr"
title = "Manuals"
theme = "book"

# code block
pygmentsCodefences = true
pygmentsStyle = "pygments"

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
#googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[params]
    # (Optional, default none) Set the path to a logo for the book. If the logo is
    # /static/logo.png then the path would be 'logo.png'
    BookLogo = 'L.png'